version: 2.1

jobs:
  test-pipefail:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: |
          exit 1 || true
          exit 1
          echo "not printed"

workflows:
  main:
    jobs:
      - test-pipefail
