version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: cimg/openjdk:13.0
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Dockerイメージについて必要なファイルを作成する
          command: |
            echo "hello" > static/index.html
      - run:
          name: Dockerイメージを作成する
          command: |
            docker build --tag my-nginx .
      - run:
          name: 作成したDockerイメージを確認する
          command: |
            docker image ls

workflows:
  main:
    jobs:
      - build-docker-image